services:
    app:
        build: .
        container_name: whatsapp-api-container
        ports:
            - 5008:5008
        env_file: .env
        environment:
            TZ: Asia/Jakarta
        volumes:
            - .:/vol/app
        networks:
            - shared-networks
networks:
    shared-networks:
        external: true
