// Import Modules
import { registerAs } from '@nestjs/config';

// Define Prefix Config App
export default registerAs('app', () => ({
    SERVICE_PORT: process.env.SERVICE_PORT,
    SERVICE_NAME: process.env.SERVICE_NAME,
    SERVICE_PREFIX: process.env.SERVICE_PREFIX,
    SERVICE_DEFAULT_VERSION: process.env.SERVICE_DEFAULT_VERSION,
    SERVICE_DOCS: process.env.SERVICE_DOCS,
    SERVICE_BASE_URL: process.env.SERVICE_BASE_URL,
    SERVICE_JWT_SECRET_KEY: process.env.SERVICE_JWT_SECRET_KEY,
    SERVICE_JWT_EXPIRES_IN: process.env.SERVICE_JWT_EXPIRES_IN,
    SERVICE_JWT_REFRESH_SECRET_KEY: process.env.SERVICE_JWT_REFRESH_SECRET_KEY,
    SERVICE_JWT_REFRESH_EXPIRES_IN: process.env.SERVICE_JWT_REFRESH_EXPIRES_IN,
    SERVICE_LIMITER_TTL: process.env.SERVICE_LIMITER_TTL,
    SERVICE_LIMITER_LIMIT: process.env.SERVICE_LIMITER_LIMIT,
    SERVICE_EMAIL_HOST: process.env.SERVICE_EMAIL_HOST,
    SERVICE_EMAIL_USER: process.env.SERVICE_EMAIL_USER,
    SERVICE_EMAIL_PASS: process.env.SERVICE_EMAIL_PASS,
    SERVICE_EMAIL_FROM: process.env.SERVICE_EMAIL_FROM,
    SERVICE_EMAIL_IMAGE: process.env.SERVICE_EMAIL_IMAGE,
    SERVICE_CRYPTO_ALGORITHM: process.env.SERVICE_CRYPTO_ALGORITHM,
    SERVICE_CRYPTO_SECRET_KEY: process.env.SERVICE_CRYPTO_SECRET_KEY,
    SERVICE_UPLOAD_PATH: process.env.SERVICE_UPLOAD_PATH,
}));
